Task.PL/Models/ErrorViewModel.cs
namespace Task.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Task.PL/Controllers/DevicesController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Task.BL.Services;
using Task.CommonDefinitions.BaseRequest;
using Task.CommonDefinitions.DTOs;
using Task.DAL.DB;
namespace Task.Controllers
{
    public class DevicesController : Controller
    {

        public readonly TaskDbContext _Context;
        public DevicesController(TaskDbContext context)
        {
            _Context = context;
        }
        public IActionResult Main()
        {
            var Response = DevicesServices.GetDevices(new BaseRequest<DeviceDTO>() { Context = _Context });
            if (Response.Success)
                return View(Response.EntityDTOs);
            else
                return View();
        }
        public IActionResult Create()
        {
            ViewBag.DeviceCategory = CategoryServices.GetCategoryes(new BaseRequest<CategoryDTO>() { Context = _Context }).EntityDTOs;
            ViewBag.Properties = PropertyServices.GetProperties(new BaseRequest<PropertyDTO> { Context = _Context}).EntityDTOs;

            return View();
        }
        [HttpPost]  
        public IActionResult Create(DeviceDTO DTO)
        {            
            var Response = DevicesServices.CreateDevice(new BaseRequest<DeviceDTO>() { Context = _Context, EntityDTO = DTO });
                return Json(Response);
        }
        public IActionResult Edit(int ID)
        {
            ViewBag.DeviceCategory = CategoryServices.GetCategoryes(new BaseRequest<CategoryDTO>() { Context = _Context }).EntityDTOs;
            ViewBag.Properties = PropertyServices.GetProperties(new BaseRequest<PropertyDTO> { Context = _Context }).EntityDTOs;

            var Response = DevicesServices.GetDevice(new BaseRequest<DeviceDTO>()
            {
                Context = _Context,
                ID = ID,
            });
            if (Response.Success)
                return View(Response.EntityDTO);
            else
                return RedirectToAction(nameof(Main));
        }
        [HttpPost]
        public IActionResult Edit(DeviceDTO DTO)
        {
            var Response = DevicesServices.EditDevice(new BaseRequest<DeviceDTO>() { Context = _Context, EntityDTO = DTO });
            return Json(Response);
        }

        public IActionResult GetProperties(int ID)
        {
            var Response = PropertyServices.GetProperties(new BaseRequest<PropertyDTO> { Context = _Context, ID = ID });

            return Json(Response);
        }
    }
}

Task.PL/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Task.PL.Controllers
{
    public class HomeController : Controller
    {

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }
    }
}

Task.PL/Views/Devices/Create.cshtml
@using Task.CommonDefinitions.DTOs;
@model DeviceDTO
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create Device</h1>
<form class="pt-3" asp-action="Create" asp-controller="Devices" id="Create-Form" method="post">
    <div class="mb-3 col-lg-6">
        <label for="DeviceName" class="form-label">Device Name</label>
        <input type="text" class="form-control" asp-for="DeviceName" placeholder="Device Name">
        <span class="text-danger field-validation-valid" asp-validation-for="DeviceName"></span>

    </div>
    <div class="mb-3 col-lg-6">
        <label for="SerialNo" class="form-label">Serial No</label>
        <input type="text" class="form-control" asp-for="SerialNo" placeholder="Serial No">
        <span class="text-danger field-validation-valid" asp-validation-for="SerialNo"></span>

    </div>
        <div class="mb-3 col-lg-6">
        <label for="AcquisitionDate" class="form-label">Acquisition Date </label>
        <input type="date" class="form-control"asp-for="AcquisitionDate" placeholder="Acquisition Date">
        <span class="text-danger field-validation-valid" asp-validation-for="AcquisitionDate"></span>

    </div>
    <div class="mb-3 col-lg-6">
        <label for="Memo" class="form-label">Memo</label>
        <input type="text" class="form-control" asp-for="Memo" placeholder="Memo">
        <span class="text-danger field-validation-valid" asp-validation-for="Memo"></span>
    </div>
    <div class="mb-3 col-lg-6">
        <label for="DeviceCategory" class="form-label">Device Category</label>
        <select asp-for="CategoryID" class="form-control" onchange="CategoryChange()"
        asp-items="@(new SelectList(ViewBag.DeviceCategory, nameof(CategoryDTO.ID), nameof(CategoryDTO.CategoryName)))">
                <option value="">--- SELECT ---</option>
        </select>
        <span class="text-danger field-validation-valid" asp-validation-for="CategoryID"></span>

    </div>
    <div class="mb-3">
        <label for="PropertiesValues" class="form-label">Properties Values</label>
        <hr />
        <div class="row">
            <form id="Props-Form" >
                @foreach (var Prop in ViewBag.Properties)
                {
                    <div class="mb-3 col-lg-6 prop d-none" data-id="Prop_@Prop.CategoryID">
                        <label for="@Prop.ID" class="form-label">@Prop.Description</label>
                        <input type="text" class="form-control propValues" placeholder="@Prop.Description">
                        <input type="hidden" class="form-control propId" value="@Prop.ID">
                    </div>
                }
            </form>
        </div>
    </div>
    <button class="btn btn-success mb-3" type="button" onclick="DevicesForm('Devices','Create','Create-Form')" id="BtnSend">
        Save  
        <span class="spinner-border Spinner spinner-border-sm d-none" role="status" aria-hidden="true"></span>
    </button>
</form>

Task.PL/Views/Devices/Edit.cshtml
@using Task.CommonDefinitions.DTOs;
@model DeviceDTO
@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create Device</h1>
<form class="pt-3" asp-action="Edit" asp-controller="Devices" id="Edit-Form" method="post">
    <div class="mb-3 col-lg-6">
        <label for="DeviceName" class="form-label">Device Name</label>
        <input type="text" class="form-control" asp-for="DeviceName"  placeholder="Device Name">
        <span class="text-danger field-validation-valid" asp-validation-for="DeviceName"></span>

    </div>
    <div class="mb-3 col-lg-6">
        <label for="SerialNo" class="form-label">Serial No</label>
        <input type="text" class="form-control" asp-for="SerialNo" placeholder="Serial No">
        <span class="text-danger field-validation-valid" asp-validation-for="SerialNo"></span>

    </div>
    <div class="mb-3 col-lg-6">
        <label for="AcquisitionDate" class="form-label">Acquisition Date </label>
        <input type="date" class="form-control" asp-for="AcquisitionDate" placeholder="Acquisition Date">
        <span class="text-danger field-validation-valid" asp-validation-for="AcquisitionDate"></span>

    </div>
    <div class="mb-3 col-lg-6">
        <label for="Memo" class="form-label">Memo</label>
        <input type="text" class="form-control" asp-for="Memo" placeholder="Memo">
        <span class="text-danger field-validation-valid" asp-validation-for="Memo"></span>
    </div>
    <div class="mb-3 col-lg-6">
        <label for="DeviceCategory" class="form-label">Device Category</label>
        <select asp-for="CategoryID" class="form-control" onchange="CategoryChange()">
            <option value="">--- SELECT ---</option>
            @foreach (var item in ViewBag.DeviceCategory)
            {
                if (Model.CategoryID == item.ID)
                {
                    <option value="@item.ID" selected>@item.CategoryName</option>
                    
                }else
                {
                  <option value="@item.ID">@item.CategoryName</option>
                }
            }
        </select>
        <span class="text-danger field-validation-valid" asp-validation-for="CategoryID"></span>
        <input type="hidden" asp-for="ID" value="@Model.ID" />
    </div>
    <div class="mb-3">
        <label for="PropertiesValues" class="form-label">Properties Values</label>
        <hr />
        <div class="row">
            <form id="Props-Form">
            @if(Model.DevicePropertiesDTOs != null)
               {
                    foreach (var Prop in Model.DevicePropertiesDTOs)
                 {
                    <div class="mb-3 col-lg-6 prop" data-id="Prop_@Model.CategoryID">
                        <label for="@Prop.ID" class="form-label">@Prop.PropertyName</label>
                        <input type="text" class="form-control propValues" value="@Prop.Value" placeholder="@Prop.PropertyName">
                        <input type="hidden" class="form-control propId" value="@Prop.ID">
                    </div>
                 }
            }

            @foreach (var Prop in ViewBag.Properties)
            {
                if (Prop.CategoryID != Model.CategoryID)
                {
                    <div class="mb-3 col-lg-6 prop d-none" data-id="Prop_@Prop.CategoryID">
                        <label for="@Prop.ID" class="form-label">@Prop.Description</label>
                        <input type="text" class="form-control propValues" placeholder="@Prop.Description">
                        <input type="hidden" class="form-control propId" value="@Prop.ID">
                    </div>
                }
            }
            </form>
        </div>
    </div>
    <button class="btn btn-success mb-3" type="button" onclick="DevicesForm('Devices','Edit','Edit-Form')" id="BtnSend">
        Save
        <span class="spinner-border Spinner spinner-border-sm d-none" role="status" aria-hidden="true"></span>
    </button>
</form>

Task.PL/Views/Devices/Main.cshtml
@using Task.CommonDefinitions.DTOs;
@model List<DeviceDTO>
@{
    ViewData["Title"] = "Main";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>All Devices</h1>
 
<div class="row justify-content-end">
    <div class="col-lg-3 d-flex justify-content-end mb-3">
        <a href="@Url.Action("Create","Devices")" class="btn btn-primary">
                 Add Device
          </a>
    </div>
</div>
<!-- Button trigger modal -->

@if (Model != null && Model.Count > 0)
{
    <div class="row">
        @foreach (var item in Model)
        {
            <div class="col-lg-3 mb-2">
                <div class="card">
                    <img src="/imgs/default.png" class="card-img-top" alt="@item.DeviceName">
                    <div class="card-body">
                        <h5 class="card-title">@item.DeviceName</h5>
                        <h6>@item.DeviceCategoryName</h6>
                        <ul class="card-text">
                           @foreach (var Pro in item.DevicePropertiesDTOs)
                           {
                              <li>
                                    @Pro.PropertyName : @Pro.Value 
                              </li> 
                           }
                        </ul>
                        <p>@item.AcquisitionDate.ToShortDateString()</p>
                        <a href="@Url.Action("Edit","Devices", new {ID = item.ID})" class="btn btn-outline-success">Edit</a>
                    </div>
                </div>
            </div>

        }

    </div>
}
else
{
    <h2 class="text-center">
        No Data Available.
</h2>
}


<!--Add Devic Modal -->
<div class="modal fade" id="staticBackdrop" data-backdrop="static" data-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="staticBackdropLabel">Modal title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                ...
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Understood</button>
            </div>
        </div>
    </div>
</div>

Task.PL/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Task.PL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Task</title>
    <link href="~/css/sweetalert2.min.css" rel="stylesheet" />
    <link href="~/css/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="@Url.Action("Main","Devices")">linked gates</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="@Url.Action("Main","Devices")">Home <span class="sr-only"></span></a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <div class="container">
            @RenderBody()
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/sweetalert2.all.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</body>
</html>